# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1257, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LoadImage = QtWidgets.QPushButton(self.groupBox)
        self.LoadImage.setObjectName("LoadImage")
        self.horizontalLayout.addWidget(self.LoadImage)
        self.View2D = QtWidgets.QPushButton(self.groupBox)
        self.View2D.setEnabled(False)
        self.View2D.setObjectName("View2D")
        self.horizontalLayout.addWidget(self.View2D)
        self.View3D = QtWidgets.QPushButton(self.groupBox)
        self.View3D.setEnabled(False)
        self.View3D.setObjectName("View3D")
        self.horizontalLayout.addWidget(self.View3D)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.Color = QtWidgets.QGroupBox(self.centralwidget)
        self.Color.setMinimumSize(QtCore.QSize(0, 80))
        self.Color.setObjectName("Color")
        self.label = QtWidgets.QLabel(self.Color)
        self.label.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.Color)
        self.Image = QtWidgets.QGroupBox(self.centralwidget)
        self.Image.setMinimumSize(QtCore.QSize(500, 650))
        self.Image.setObjectName("Image")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Image)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Image)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.Image)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ShowPredict = QtWidgets.QPushButton(self.groupBox_3)
        self.ShowPredict.setObjectName("ShowPredict")
        self.horizontalLayout_2.addWidget(self.ShowPredict)
        self.HidePredict = QtWidgets.QPushButton(self.groupBox_3)
        self.HidePredict.setObjectName("HidePredict")
        self.horizontalLayout_2.addWidget(self.HidePredict)
        self.ShowLabel = QtWidgets.QPushButton(self.groupBox_3)
        self.ShowLabel.setObjectName("ShowLabel")
        self.horizontalLayout_2.addWidget(self.ShowLabel)
        self.HideLabel = QtWidgets.QPushButton(self.groupBox_3)
        self.HideLabel.setObjectName("HideLabel")
        self.horizontalLayout_2.addWidget(self.HideLabel)
        self.SaveFig = QtWidgets.QPushButton(self.groupBox_3)
        self.SaveFig.setObjectName("SaveFig")
        self.horizontalLayout_2.addWidget(self.SaveFig)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LoadImage.setText(_translate("MainWindow", "LoadImage"))
        self.View2D.setText(_translate("MainWindow", "View2D"))
        self.View3D.setText(_translate("MainWindow", "View3D"))
        self.Color.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "LabelColor"))
        self.Image.setTitle(_translate("MainWindow", "image"))
        self.ShowPredict.setText(_translate("MainWindow", "ShowPredict"))
        self.HidePredict.setText(_translate("MainWindow", "HidePredict"))
        self.ShowLabel.setText(_translate("MainWindow", "ShowLabel"))
        self.HideLabel.setText(_translate("MainWindow", "HideLabel"))
        self.SaveFig.setText(_translate("MainWindow", "SaveFig"))

